version: "3.7"

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: databasePassword
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  hasura:
    image: hasura/graphql-engine:v1.2.0-beta.3.cli-migrations-v2
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:databasePassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "hasuraSecret"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
    volumes:
      - type: bind
        source: ./metadata
        target: /hasura-metadata
        read_only: true

      - type: bind
        source: ./migrations
        target: /hasura-migrations
        read_only: true

volumes:
  database:
    name: "GraphQLIntroPostgreSQL"
